# Generated by Django 4.1.7 on 2023-02-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='sluf',
            new_name='slug',
        ),
    ]
